# Generated by Django 3.0.3 on 2020-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantfamily',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
